services:
  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    image: itzcrazykns1337/perplexica-backend:main
    environment:
      - SERVICE_FQDN_BACKEND_3001
      - 'SEARXNG_API_URL=${SEARXNG_API_URL}'
    volumes:
      - 'backend-dbstore:/home/perplexica/data'
      - 'uploads:/home/perplexica/uploads'
      - './config.toml:/home/perplexica/config.toml'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped

  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${SERVICE_FQDN_BACKEND_3001}/api
        - NEXT_PUBLIC_WS_URL=ws://127.0.0.1:3001
    image: itzcrazykns1337/perplexica-frontend:main
    environment:
      - SERVICE_FQDN_FRONTEND_3000
    depends_on:
      - perplexica-backend
    restart: unless-stopped

networks:
  perplexica-network:

volumes:
  backend-dbstore:
  uploads:
